//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernAudioSwitcher.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernAudioSwitcher.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Run 的本地化字符串。
        /// </summary>
        public static string AutoRun {
            get {
                return ResourceManager.GetString("AutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Preset 的本地化字符串。
        /// </summary>
        public static string CreatePreset {
            get {
                return ResourceManager.GetString("CreatePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Commu Device 的本地化字符串。
        /// </summary>
        public static string DefaultCommuDevice {
            get {
                return ResourceManager.GetString("DefaultCommuDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Device 的本地化字符串。
        /// </summary>
        public static string DefaultDevice {
            get {
                return ResourceManager.GetString("DefaultDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Media Device 的本地化字符串。
        /// </summary>
        public static string DefaultMediaDevice {
            get {
                return ResourceManager.GetString("DefaultMediaDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Devices 的本地化字符串。
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no preset here, please add some 的本地化字符串。
        /// </summary>
        public static string NoPresetTips {
            get {
                return ResourceManager.GetString("NoPresetTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon NotificationArea {
            get {
                object obj = ResourceManager.GetObject("NotificationArea", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback Devices 的本地化字符串。
        /// </summary>
        public static string PlabackDevices {
            get {
                return ResourceManager.GetString("PlabackDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PresetDescription 的本地化字符串。
        /// </summary>
        public static string PresetDescription {
            get {
                return ResourceManager.GetString("PresetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preset Name 的本地化字符串。
        /// </summary>
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presets 的本地化字符串。
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record Devices 的本地化字符串。
        /// </summary>
        public static string RecordDevices {
            get {
                return ResourceManager.GetString("RecordDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set As 的本地化字符串。
        /// </summary>
        public static string SetAs {
            get {
                return ResourceManager.GetString("SetAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
    }
}
