//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioSwitcher {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AudioSwitcher.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Appearance 的本地化字符串。
        /// </summary>
        internal static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Automatically switch to plugged in device 的本地化字符串。
        /// </summary>
        internal static string AutomaticallySwitchToPluggedInDevice {
            get {
                return ResourceManager.GetString("AutomaticallySwitchToPluggedInDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DefaultCommunicationsDevice {
            get {
                object obj = ResourceManager.GetObject("DefaultCommunicationsDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DefaultMultimediaDevice {
            get {
                object obj = ResourceManager.GetObject("DefaultMultimediaDevice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string DeviceState_Active {
            get {
                return ResourceManager.GetString("DeviceState_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default communications device 的本地化字符串。
        /// </summary>
        internal static string DeviceState_DefaultCommunicationsDevice {
            get {
                return ResourceManager.GetString("DeviceState_DefaultCommunicationsDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default device 的本地化字符串。
        /// </summary>
        internal static string DeviceState_DefaultDevice {
            get {
                return ResourceManager.GetString("DeviceState_DefaultDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default multimedia device 的本地化字符串。
        /// </summary>
        internal static string DeviceState_DefaultMultimediaDevice {
            get {
                return ResourceManager.GetString("DeviceState_DefaultMultimediaDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        internal static string DeviceState_Disabled {
            get {
                return ResourceManager.GetString("DeviceState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not present 的本地化字符串。
        /// </summary>
        internal static string DeviceState_NotPresent {
            get {
                return ResourceManager.GetString("DeviceState_NotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not plugged in 的本地化字符串。
        /// </summary>
        internal static string DeviceState_Unplugged {
            get {
                return ResourceManager.GetString("DeviceState_Unplugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Disabled {
            get {
                object obj = ResourceManager.GetObject("Disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 E&amp;xit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon FallbackDevice {
            get {
                object obj = ResourceManager.GetObject("FallbackDevice", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 No devices selected 的本地化字符串。
        /// </summary>
        internal static string NoDevices {
            get {
                return ResourceManager.GetString("NoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No playback devices 的本地化字符串。
        /// </summary>
        internal static string NoPlaybackDevices {
            get {
                return ResourceManager.GetString("NoPlaybackDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No recording devices 的本地化字符串。
        /// </summary>
        internal static string NoRecordingDevices {
            get {
                return ResourceManager.GetString("NoRecordingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon NotificationArea {
            get {
                object obj = ResourceManager.GetObject("NotificationArea", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap NotPresent {
            get {
                object obj = ResourceManager.GetObject("NotPresent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Run at Windows startup 的本地化字符串。
        /// </summary>
        internal static string RunAtStartup {
            get {
                return ResourceManager.GetString("RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set as default &amp;communication device 的本地化字符串。
        /// </summary>
        internal static string SetAsDefaultComunicationDevice {
            get {
                return ResourceManager.GetString("SetAsDefaultComunicationDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set as default &amp;multimedia device 的本地化字符串。
        /// </summary>
        internal static string SetAsDefaultMultimediaDevice {
            get {
                return ResourceManager.GetString("SetAsDefaultMultimediaDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Settings 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Disabled devices 的本地化字符串。
        /// </summary>
        internal static string ShowDisabledDevices {
            get {
                return ResourceManager.GetString("ShowDisabledDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Not present devices 的本地化字符串。
        /// </summary>
        internal static string ShowNotPresentDevices {
            get {
                return ResourceManager.GetString("ShowNotPresentDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Playback devices 的本地化字符串。
        /// </summary>
        internal static string ShowPlaybackDevices {
            get {
                return ResourceManager.GetString("ShowPlaybackDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Recording devices 的本地化字符串。
        /// </summary>
        internal static string ShowRecordingDevices {
            get {
                return ResourceManager.GetString("ShowRecordingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Unplugged devices 的本地化字符串。
        /// </summary>
        internal static string ShowUnpluggedDevices {
            get {
                return ResourceManager.GetString("ShowUnpluggedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Switcher 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Unplugged {
            get {
                object obj = ResourceManager.GetObject("Unplugged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
